#!/bin/bash

#SBATCH -n 4                              # Number of cores
#SBATCH --time=1:00:00                    # hours:minutes:seconds
#SBATCH --mem-per-cpu=30000
#SBATCH --tmp=4000                         # per node!!
#SBATCH  --gpus=rtx_2080_ti:1              # Ohter options are: --gpus=gtx_1080_ti:1  --gpus=rtx_2080_ti:1
#SBATCH --job-name=saga_16d_with_ptloss
#SBATCH --output=./results/saga_16d_with_ptloss_table/saga_16d_with_ptloss_counter.out
#SBATCH --error=./results/saga_16d_with_ptloss_table/saga_16d_with_ptloss_counter.err


module load gcc/8.2.0 python_gpu/3.10.4 boost/1.74.0 eth_proxy open3d/0.9.0
source /cluster/scratch/yaqqin/venvs/flex_venv/bin/activate
module load gcc/8.2.0 python_gpu/3.10.4 boost/1.74.0 eth_proxy open3d/0.9.0
python opt_grasppose_flex.py --exp_name saga_with_flex_latentz --gender male --pose_ckpt_path pretrained_model/male_grasppose_model.pt --n_rand_samples_per_object 1 --object camera